// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXcmjVHm3w1YCR6MdF7CI5H55Tbp8vUUs',
    appId: '1:39120890961:web:d498c2f174395a0a269c70',
    messagingSenderId: '39120890961',
    projectId: 'e-agriculture-system-90979',
    authDomain: 'e-agriculture-system-90979.firebaseapp.com',
    storageBucket: 'e-agriculture-system-90979.firebasestorage.app',
    measurementId: 'G-SWDR45PRPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3AOHbeLdZ8_24JehNBRlDm_Pa2204B-I',
    appId: '1:39120890961:android:06b74edd1fb7d135269c70',
    messagingSenderId: '39120890961',
    projectId: 'e-agriculture-system-90979',
    storageBucket: 'e-agriculture-system-90979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACNdnWL5xvtGqPn3XbWNHizmcxqqaqbp0',
    appId: '1:39120890961:ios:f7e9890fbfd4ab39269c70',
    messagingSenderId: '39120890961',
    projectId: 'e-agriculture-system-90979',
    storageBucket: 'e-agriculture-system-90979.firebasestorage.app',
    iosBundleId: 'com.example.eAgricultureSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACNdnWL5xvtGqPn3XbWNHizmcxqqaqbp0',
    appId: '1:39120890961:ios:f7e9890fbfd4ab39269c70',
    messagingSenderId: '39120890961',
    projectId: 'e-agriculture-system-90979',
    storageBucket: 'e-agriculture-system-90979.firebasestorage.app',
    iosBundleId: 'com.example.eAgricultureSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXcmjVHm3w1YCR6MdF7CI5H55Tbp8vUUs',
    appId: '1:39120890961:web:945a3ae32abf05f8269c70',
    messagingSenderId: '39120890961',
    projectId: 'e-agriculture-system-90979',
    authDomain: 'e-agriculture-system-90979.firebaseapp.com',
    storageBucket: 'e-agriculture-system-90979.firebasestorage.app',
    measurementId: 'G-3E9T8MQ5X6',
  );

}